on: [push]
name: Deploy SQL to DB
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: tgg-oms-psql
    steps:

      # Deploy SQL template
    - name: Run SQL Script
      uses: bytebase/sql-review-action@main
      with:
        database-type: "POSTGRES"
        file-pattern: "tst_schema.sql"
