name: PostgreSQL for GitHub Actions

on:
  push:
    branches: [ main ]

  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/actions/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
